/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutButton: typeof import('./src/components/BottomBar/AboutButton.vue')['default']
    Archive: typeof import('./src/components/Archive.vue')['default']
    BottomBar: typeof import('./src/components/BottomBar/BottomBar.vue')['default']
    Button: typeof import('primevue/button')['default']
    ButtonC: typeof import('./src/components/ButtonC.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    copy: typeof import('./src/components/BottomBar/HomeButton copy.vue')['default']
    ExperienceButton: typeof import('./src/components/BottomBar/ExperienceButton.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HomeButton: typeof import('./src/components/BottomBar/HomeButton.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputGroupAddon: typeof import('primevue/inputgroupaddon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Panel: typeof import('primevue/panel')['default']
    Popover: typeof import('primevue/popover')['default']
    PortfolioButton: typeof import('./src/components/BottomBar/PortfolioButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsPopover: typeof import('./src/components/BottomBar/SettingsPopover.vue')['default']
    Skeleton: typeof import('primevue/skeleton')['default']
    SkeletonLoader: typeof import('./src/components/SkeletonLoader/SkeletonLoader.vue')['default']
    Slider: typeof import('primevue/slider')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
    ToggleSwitchC: typeof import('./src/components/ToggleSwitchC.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
  export interface ComponentCustomProperties {
    AnimateOnScroll: typeof import('primevue/animateonscroll')['default']
  }
}
